CREATE DATABASE gateway_db;
CREATE DATABASE user_db;
CREATE DATABASE staff_db;
CREATE DATABASE product_db;
CREATE DATABASE cart_db;
CREATE DATABASE comment_db;
CREATE DATABASE order_db;
CREATE DATABASE payment_db;
CREATE DATABASE shipping_db;

GRANT ALL PRIVILEGES ON DATABASE gateway_db TO root;
GRANT ALL PRIVILEGES ON DATABASE user_db TO root;
GRANT ALL PRIVILEGES ON DATABASE staff_db TO root;
GRANT ALL PRIVILEGES ON DATABASE product_db TO root;
GRANT ALL PRIVILEGES ON DATABASE cart_db TO root;
GRANT ALL PRIVILEGES ON DATABASE comment_db TO root;
GRANT ALL PRIVILEGES ON DATABASE order_db TO root;
GRANT ALL PRIVILEGES ON DATABASE payment_db TO root;
GRANT ALL PRIVILEGES ON DATABASE shipping_db TO root;
