# Generated by Django 6.0.4 on 2026-06-08 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=16)),
                ('target_id', models.UUIDField()),
                ('action', models.CharField(choices=[('HIDE', 'Hide'), ('SHOW', 'Show')], max_length=16)),
                ('moderated_by', models.UUIDField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden')], default='VISIBLE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.UUIDField()),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden')], default='VISIBLE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.review')),
            ],
        ),
    ]
